# Default uses the following labels typical for a Kanban board.
# The 26 labels belong to 4 groups: effort, type, priority & work
# Preview: https://github.com/varunvora/github-label-manager/labels

# Agile uses the Fibonacci sequence for effort-estimation
- name: "effort: 1"
  color: "fff2cc"
  description: ""
- name: "effort: 2"
  color: "ffecb3"
  description: ""
- name: "effort: 3"
  color: "ffe699"
  description: ""
- name: "effort: 5"
  color: "ffd966"
  description: ""
- name: "effort: 8"
  color: "ffcc33"
  description: ""
- name: "effort: 13"
  color: "ffbf00"
  description: ""

# Priority
- name: "priority: critical"
  color: "ff3333"
  description: "Pick this NOW!"
- name: "priority: high"
  color: "ff6666"
  description: "Pick this ASAP"
- name: "priority: medium"
  color: "ff9999"
  description: "Pick this as per plan"
- name: "priority: low"
  color: "ffcccc"
  description: "Pick this when there is nothing else to pick"

# Type of the task
- name: "type: poc"
  color: "4dd2ff"
  description: "Proof of concept"
- name: "type: docs"
  color: "b3ecff"
  description: "Changes to documentation"
- name: "type: test"
  color: "66d9ff"
  description: "Changes in tests without any change in logic"
- name: "type: feature"
  color: "1ac6ff"
  description: "New feature for the user"
- name: "type: optimize"
  color: "80dfff"
  description: "Optimize existing code"
- name: "type: chore"
  color: "e6f9ff"
  description: "Updating grunt tasks without any change in logic"
- name: "type: style"
  color: "99e6ff"
  description: "Formatting and tidying without any change in logic"
- name: "type: bug/fix"
  color: "33ccff"
  description: "A bug or a fix"
- name: "type: discussion"
  color: "ccf2ff"
  description: "Discussion"

# Complexity of the task based on Cynefin framework
- name: "work: chaotic"
  color: "999999"
  description: "The cause and effect are unclear"
- name: "work: complex"
  color: "b3b3b3"
  description: "The cause and effect can only be deduced in retrospect, and there are no right answers"
- name: "work: complicated"
  color: "cccccc"
  description: "The cause and effect requires analysis; there are a range of right answers"
- name: "work: obvious"
  color: "e6e6e6"
  description: "The cause and effect is clear"
